### PR TITLE
delete overlap micropost-spec

### PR DESCRIPTION
**Pull request by paveg**

### CODE REVIEW

**Comment by yasulab** [comment]
This code seems to be added from the [section 10.1.2 in Rails Tutorial in Japanese (2e)](http://railstutorial.jp/chapters/user-microposts?version=4.0#sec-first_micropost_validation). So, I think this code is needed to be the sample of Sample Application. Any ideas?

**Comment by paveg** [comment]
hi! thanks for your reply.
Certainly, this code seems to be added from the <a href="http://railstutorial.jp/chapters/user-microposts?version=4.0#sec-first_micropost_validation>section 10.1.2 in Rails Tutorial in Japanese (2e)</a>. but, I thought duplicated code.

**Comment by yasulab** [comment]
> I thought it was duplicated.

Can you tell me which code (or which listing) is duplicated to this code?

**Comment by yasulab** [comment]
Oops, sorry! I've misunderstood that this PR is to fix the text, but this is just for fixing my typo on this repository :sweat_drops: Thanks!

**Comment by yasulab** [comment]
And sorry for wasting your time to my misunderstanding ><

**Pull request merged**
